### PR TITLE
Update MetaCat metadata format

### PR DESCRIPTION
**Pull request by mjkramer**
The ingest daemon expects the metadata filename to be just the data filename + .json.

### CODE REVIEW

**Review by akeemlh — APPROVED** [review]
In that case, we may also need to change line 92 where the default arguments get overwritten. But for now LGTM

**Comment by mjkramer** [comment]
For the sake of keeping track, here are the other fixes I intend to include in this PR:
- [ ] Get rid of `created_timestamp`
- [ ] Make core.runs a single-element list
- [ ] Make core.runs_subruns use a predictable value (power_of_10 * run + (file_index)) instead of the arbitrary counter that currently gets written
- [ ] Zero-pad the checksum to 8 characters

**Comment by mjkramer** [comment]
ref https://github.com/DUNE/data-mgmt-ops/issues/670

**Comment by hschellman** [comment]
Also can you please add:

 “core.file_content_status”: “good”

so far it seems to be the only missing field.  Hard to check if it isn't there.

**Review by akeemlh — APPROVED** [review]
LGTM. Approved

**Pull request merged**
